// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDn6T6pIMzEzFASFtv6g3JAU87j3Q2W8hY',
    appId: '1:542232190217:web:51adab4aca8c2548dac7d8',
    messagingSenderId: '542232190217',
    projectId: 'voyageph-9e067',
    authDomain: 'voyageph-9e067.firebaseapp.com',
    storageBucket: 'voyageph-9e067.firebasestorage.app',
    measurementId: 'G-RG3TQ7JPP0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH4iMbHfS60B6IkD2up2RDzghvfxCI7cI',
    appId: '1:542232190217:android:d55f5b0283cb91f1dac7d8',
    messagingSenderId: '542232190217',
    projectId: 'voyageph-9e067',
    storageBucket: 'voyageph-9e067.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDafFXIMINJ6_zvjREG5xfkm3Sjve1iXIQ',
    appId: '1:542232190217:ios:60a8b85dc2baef5adac7d8',
    messagingSenderId: '542232190217',
    projectId: 'voyageph-9e067',
    storageBucket: 'voyageph-9e067.firebasestorage.app',
    iosBundleId: 'com.example.voyageph',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDafFXIMINJ6_zvjREG5xfkm3Sjve1iXIQ',
    appId: '1:542232190217:ios:60a8b85dc2baef5adac7d8',
    messagingSenderId: '542232190217',
    projectId: 'voyageph-9e067',
    storageBucket: 'voyageph-9e067.firebasestorage.app',
    iosBundleId: 'com.example.voyageph',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDn6T6pIMzEzFASFtv6g3JAU87j3Q2W8hY',
    appId: '1:542232190217:web:539465e615220f30dac7d8',
    messagingSenderId: '542232190217',
    projectId: 'voyageph-9e067',
    authDomain: 'voyageph-9e067.firebaseapp.com',
    storageBucket: 'voyageph-9e067.firebasestorage.app',
    measurementId: 'G-EZ707TXYCR',
  );
}
